= Manuscript Example

[quote, Someone]
____
Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...

There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...
____


[role="first-pagraph"]
Lorem "ipsum dolor sit amet", "`consectetur adipiscing`" elit. Nam mollis elementum lectus, vel pellentesque ex varius consequat. Sed in odio semper, elementum lorem ut, fringilla augue. Integer mattis, lorem a facilisis maximus, neque dolor sodales leo, sit amet eleifend augue quam varius nisl. Aliquam eleifend risus sit amet orci `commodo mollis`. Duis sit amet nunc rhoncus dui rhoncus finibus et non odio. Maecenas aliquet orci quis tortor finibus lobortis. Praesent dictum dictum nibh `pulvinar "posuere"`. Proin in iaculis turpis. Ut id orci vitae lectus sagittis accumsan. 

For this, see <<sub-a>>.

For that, see <<sub-c>>.

[source, bash]
----
FN_EXAMPLE = "This is a string"
"Some other"
----

include::include.adoc[]

Fusce lobortis orci justo, a porta ipsum tristique nec. Mauris molestie, enim vitae pretium tincidunt, lorem nibh vestibulum justo, in euismod enim mi id mauris. Nulla vel libero id sem rutrum interdum nec at nulla. Cras eleifend iaculis interdum.footnote:[Proin mattis sit amet tortor at facilisis. Aenean viverra suscipit fermentum.] Maecenas cursus viverra elit nec aliquet. Aliquam pulvinar volutpat odio nec consectetur.

[role="test-verse"]
[verse]
____

Roses are red, violets are blue
Let me just say, "I love you."
____

Suspendisse justo diam, pretium quis ex sed, scelerisque hendrerit felis. Donec maximus ante id nisi pellentesque, sit amet vulputate arcu fringilla. Nam aliquam eu ante in tincidunt. Duis vel nunc augue. Nam vel nulla nec justo eleifend fringilla. Suspendisse tempor iaculis blandit. Aenean mauris neque, iaculis vel mauris id, consequat maximus sem. Nunc vitae gravida odio. In ex magna, viverra id elit quis, lacinia fermentum enim. Nullam ante felis, euismod sit amet odio eu, sollicitudin varius mauris. Proin quis massa ac ante pulvinar interdum vitae a quam.

[[sub-a]]
== Heading One

Nulla luctus fringilla ipsum, egestas congue mi malesuada eget. Maecenas placerat quis metus eget pulvinar. Aliquam aliquam felis mauris, nec convallis est dictum a. Ut vitae ultrices nulla. Aliquam porttitor tortor pretium, elementum leo elementum, venenatis velit. Integer volutpat odio et nunc elementum, vitae tristique eros hendrerit. Mauris sit amet porta nunc, ut lacinia leo. Nullam nec viverra lacus. Ut felis odio, rhoncus nec magna vitae, mollis cursus neque. Integer et sagittis velit. Vestibulum vel vulputate urna. Praesent eget volutpat nunc.

[options="header"]
.Table example
|===
| Heading A | Heading B

| one      | two      
| three    | four     
| five     | six      
|===

Fusce nisi sapien, efficitur et venenatis nec, congue ac dolor. Suspendisse tempus nisi sed suscipit interdum. Nunc vel mauris nibh. Donec nisi libero, suscipit id nunc quis, ullamcorper dapibus mauris. Aliquam quam orci, tempus non tempor a, dictum in metus. Nam lacus sem, interdum quis condimentum at, luctus in massa. Integer odio elit, tempus vitae dictum id, tristique id augue. Ut fermentum, justo at dapibus dapibus, leo orci cursus ante, vel egestas mi eros sit amet arcu. Mauris viverra nisi sit amet tortor tristique condimentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus et faucibus tortor.
